# permissions for end users to edit obzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: obzone-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ob-operator-generate
    app.kubernetes.io/part-of: ob-operator-generate
    app.kubernetes.io/managed-by: kustomize
  name: obzone-editor-role
rules:
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obzones/status
  verbs:
  - get
