# permissions for end users to edit obzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obzone-editor-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - obzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - obzones/status
  verbs:
  - get
