# permissions for end users to view obzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obzone-viewer-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - obzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - obzones/status
  verbs:
  - get
