# permissions for end users to view rootservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rootservice-viewer-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - rootservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - rootservices/status
  verbs:
  - get
