# permissions for end users to edit rootservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rootservice-editor-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - rootservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - rootservices/status
  verbs:
  - get
