# permissions for end users to edit statefulapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulapp-editor-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - statefulapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - statefulapps/status
  verbs:
  - get
