apiVersion: cloud.oceanbase.com/v2alpha1
kind: OBCluster
metadata:
  name: test
  namespace: oceanbase
spec:
  clusterName: obcluster
  clusterId: 1
  userSecrets:
    root: test-user-root
    proxyro: test-user-proxy
    monitor: test-user-monitor
    operator: test-user-operator
  topology:
    - zone: zone1
      replica: 1
      nodeSelector:
        ob.zone: zone1
  observer:
    image: oceanbasedev/oceanbase-cn:v4.1.0.0-100000192023032010
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: local-path
        size: 50Gi
      redoLogStorage:
        storageClass: local-path
        size: 50Gi
      logStorage:
        storageClass: local-path
        size: 20Gi
  monitor:
    image: oceanbase/obagent:1.2.0
    resource:
      cpu: 2
      memory: 4Gi
    storage:
      configStorage:
        storageClass: local-path
        size: 1Gi
  parameters:
    - name: log_disk_size
      value: 40G
  backupVolume:
    volume:
      name: backup
      nfs:
        server: 11.124.9.57
        path: /opt/nfs
        readOnly: false
