apiVersion: oceanbase.oceanbase.com/v2alpha1
kind: OBClusterRestore
metadata:
  labels:
    app.kubernetes.io/name: obclusterrestore
    app.kubernetes.io/instance: obclusterrestore-sample
    app.kubernetes.io/part-of: ob-operator-generate
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ob-operator-generate
  name: obclusterrestore-sample
spec:
  # TODO(user): Add fields here
