apiVersion: cloud.oceanbase.com/v2alpha1
kind: OBUnit
metadata:
  labels:
    app.kubernetes.io/name: obunit
    app.kubernetes.io/instance: obunit-sample
    app.kubernetes.io/part-of: ob-operator-generate
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ob-operator-generate
  name: obunit-sample
spec:
  # TODO(user): Add fields here
