apiVersion: cloud.oceanbase.com/v1
kind: StatefulApp
metadata:
  namespace: ob
  name: sapp
spec:
  cluster: cn  # Operator 监控的集群名称，启动的时候需要指定
  subsets:
  - name: zone1
    nodeSelector:  # 强制匹配到某个 Zone
      topology.kubernetes.io/zone: zone1
    replicas: 2
  - name: zone2
    nodeSelector:
      topology.kubernetes.io/zone: zone2
    replicas: 1
  - name: zone3
    nodeSelector:
      topology.kubernetes.io/zone: zone3
    replicas: 1
  podTemplate:  # Pod 自身资源的描述
    containers:
      - name: observer
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
          - name: log
            mountPath: /home/admin/oceanbase/log
          - name: data
            mountPath: /home/admin/oceanbase/store
    volumes:
      - name: log
        persistentVolumeClaim:
          claimName: log
      - name: data
        persistentVolumeClaim:
          claimName: data
  storageTemplates:  # 对 Pod 所依赖的存储的描述
  - name: log
    pvc:
      accessModes:
        - ReadWriteOnce
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
  - name: data
    pvc:
      accessModes:
          - ReadWriteOnce
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
status:
  cluster: cn
  clusterStatus: Ready
  subsets:
  - name: zone1
    expectedReplicas: 3
    availableReplicas: 1
    pods:
    - name: sapp-1
      index: 0
      podPhase: Running
      podIP: 10.10.10.1
      nodeIP: 1.1.1.1
      pvcs:
      - name: sapp-cn-zone1-0-data-store
        phase: Bound
