apiVersion: oceanbase.oceanbase.com/v2alpha1
kind: OBTenantRestore
metadata:
  labels:
    app.kubernetes.io/name: obtenantrestore
    app.kubernetes.io/instance: obtenantrestore-sample
    app.kubernetes.io/part-of: ob-operator-generate
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ob-operator-generate
  name: obtenantrestore-sample
spec:
  # TODO(user): Add fields here
