apiVersion: cloud.oceanbase.com/v1
kind: OBZone
metadata:
  labels:
    app: ob-test
  name: obzone-ob-test
  namespace: ob
spec:
  topology:
    - cluster: cn
      zone:
      - name: zone1
        region: region1
        nodeSelector:
          topology.kubernetes.io/zone: zone1
        replicas: 1
      - name: zone2
        region: region1
        nodeSelector:
          topology.kubernetes.io/zone: zone2
        replicas: 1
      - name: zone3
        region: region1
        nodeSelector:
          topology.kubernetes.io/zone: zone3
        replicas: 1
status:
  topology:
  - cluster: cn
    zone:
    - name: zone1
      nodes:
      - serverIP: 10.10.10.1
        status: active
    - name: zone2
      nodes:
      - serverIP: 10.10.10.2
        status: active
    - name: zone3
      nodes:
      - serverIP: 10.10.10.3
        status: active
