apiVersion: oceanbase.oceanbase.com/v2alpha1
kind: OBServer
metadata:
  labels:
    app.kubernetes.io/name: observer
    app.kubernetes.io/instance: observer-sample
    app.kubernetes.io/part-of: ob-operator-generate
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ob-operator-generate
  name: observer-sample
spec:
  # TODO(user): Add fields here
